// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: blnk.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input map[string]string `protobuf:"bytes,2,rep,name=Input,proto3" json:"Input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HeaderArray) Reset() {
	*x = HeaderArray{}
	mi := &file_blnk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderArray) ProtoMessage() {}

func (x *HeaderArray) ProtoReflect() protoreflect.Message {
	mi := &file_blnk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderArray.ProtoReflect.Descriptor instead.
func (*HeaderArray) Descriptor() ([]byte, []int) {
	return file_blnk_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderArray) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

// GRequest represents a generic transaction request
type GRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header []*HeaderArray `protobuf:"bytes,1,rep,name=Header,proto3" json:"Header,omitempty"`
	Path   string         `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method string         `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Body   string         `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GRequest) Reset() {
	*x = GRequest{}
	mi := &file_blnk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRequest) ProtoMessage() {}

func (x *GRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blnk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRequest.ProtoReflect.Descriptor instead.
func (*GRequest) Descriptor() ([]byte, []int) {
	return file_blnk_proto_rawDescGZIP(), []int{1}
}

func (x *GRequest) GetHeader() []*HeaderArray {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// GResponse represents a generic transaction response
type GResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseCode int32  `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseMsg  string `protobuf:"bytes,2,opt,name=response_msg,json=responseMsg,proto3" json:"response_msg,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Body         string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GResponse) Reset() {
	*x = GResponse{}
	mi := &file_blnk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GResponse) ProtoMessage() {}

func (x *GResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blnk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GResponse.ProtoReflect.Descriptor instead.
func (*GResponse) Descriptor() ([]byte, []int) {
	return file_blnk_proto_rawDescGZIP(), []int{2}
}

func (x *GResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *GResponse) GetResponseMsg() string {
	if x != nil {
		return x.ResponseMsg
	}
	return ""
}

func (x *GResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_blnk_proto protoreflect.FileDescriptor

var file_blnk_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x6c, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x76, 0x0a, 0x08, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x7f, 0x0a, 0x09, 0x47, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0x3d, 0x0a, 0x0b, 0x42, 0x6c,
	0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x53, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blnk_proto_rawDescOnce sync.Once
	file_blnk_proto_rawDescData = file_blnk_proto_rawDesc
)

func file_blnk_proto_rawDescGZIP() []byte {
	file_blnk_proto_rawDescOnce.Do(func() {
		file_blnk_proto_rawDescData = protoimpl.X.CompressGZIP(file_blnk_proto_rawDescData)
	})
	return file_blnk_proto_rawDescData
}

var file_blnk_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blnk_proto_goTypes = []any{
	(*HeaderArray)(nil), // 0: proto.HeaderArray
	(*GRequest)(nil),    // 1: proto.GRequest
	(*GResponse)(nil),   // 2: proto.GResponse
	nil,                 // 3: proto.HeaderArray.InputEntry
}
var file_blnk_proto_depIdxs = []int32{
	3, // 0: proto.HeaderArray.Input:type_name -> proto.HeaderArray.InputEntry
	0, // 1: proto.GRequest.Header:type_name -> proto.HeaderArray
	1, // 2: proto.BlnkService.GSender:input_type -> proto.GRequest
	2, // 3: proto.BlnkService.GSender:output_type -> proto.GResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blnk_proto_init() }
func file_blnk_proto_init() {
	if File_blnk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blnk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blnk_proto_goTypes,
		DependencyIndexes: file_blnk_proto_depIdxs,
		MessageInfos:      file_blnk_proto_msgTypes,
	}.Build()
	File_blnk_proto = out.File
	file_blnk_proto_rawDesc = nil
	file_blnk_proto_goTypes = nil
	file_blnk_proto_depIdxs = nil
}
