// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: blnk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlnkService_GSender_FullMethodName = "/proto.BlnkService/GSender"
)

// BlnkServiceClient is the client API for BlnkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Blnk service definition
type BlnkServiceClient interface {
	GSender(ctx context.Context, in *GRequest, opts ...grpc.CallOption) (*GResponse, error)
}

type blnkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlnkServiceClient(cc grpc.ClientConnInterface) BlnkServiceClient {
	return &blnkServiceClient{cc}
}

func (c *blnkServiceClient) GSender(ctx context.Context, in *GRequest, opts ...grpc.CallOption) (*GResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GResponse)
	err := c.cc.Invoke(ctx, BlnkService_GSender_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlnkServiceServer is the server API for BlnkService service.
// All implementations must embed UnimplementedBlnkServiceServer
// for forward compatibility.
//
// Blnk service definition
type BlnkServiceServer interface {
	GSender(context.Context, *GRequest) (*GResponse, error)
	mustEmbedUnimplementedBlnkServiceServer()
}

// UnimplementedBlnkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlnkServiceServer struct{}

func (UnimplementedBlnkServiceServer) GSender(context.Context, *GRequest) (*GResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GSender not implemented")
}
func (UnimplementedBlnkServiceServer) mustEmbedUnimplementedBlnkServiceServer() {}
func (UnimplementedBlnkServiceServer) testEmbeddedByValue()                     {}

// UnsafeBlnkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlnkServiceServer will
// result in compilation errors.
type UnsafeBlnkServiceServer interface {
	mustEmbedUnimplementedBlnkServiceServer()
}

func RegisterBlnkServiceServer(s grpc.ServiceRegistrar, srv BlnkServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlnkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlnkService_ServiceDesc, srv)
}

func _BlnkService_GSender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlnkServiceServer).GSender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlnkService_GSender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlnkServiceServer).GSender(ctx, req.(*GRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlnkService_ServiceDesc is the grpc.ServiceDesc for BlnkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlnkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BlnkService",
	HandlerType: (*BlnkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GSender",
			Handler:    _BlnkService_GSender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blnk.proto",
}
